## 元素级乘法
你已看过了一些元素级乘法。你可以使用 multiply 函数或 * 运算符来实现。回顾一下，它看起来是这样的：



In [1]:
import numpy as np
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
n = m * 0.25
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [3]:
m * n


array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [4]:
np.multiply(m, n)   #相当于 m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

## 矩阵乘积
要获得矩阵乘积，你可以使用 NumPy 的 matmul 函数。


In [5]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
a.shape

(2, 4)

In [7]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
b.shape


(4, 3)

In [9]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [10]:
c.shape

(2, 3)

In [11]:
np.matmul(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
NumPy 的 dot 函数
有时候，在你以为要用 matmul 函数的地方，你可能会看到 NumPy 的 dot 函数。事实证明，如果矩阵是二维的，那么 dot 和 matmul 函数的结果是相同的。

所以这两个结果是等价的：

In [25]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [37]:
np.dot(a,a)



array([[ 7, 10],
       [15, 22]])

In [38]:
a = np.array([[1,2],[3,4]])
a.dot(a)  # you can call你可以直接对 `ndarray` 调用 `dot`


array([[ 7, 10],
       [15, 22]])

In [39]:
np.matmul(a,a)


array([[ 7, 10],
       [15, 22]])

## 转置

NumPy 在进行转置时不会实际移动内存中的任何数据 - 只是改变对原始矩阵的索引方式 - 所以是非常高效的。




In [45]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [46]:
m.T


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

但是，这也意味着你要特别注意修改对象的方式，因为它们共享相同的数据。例如，对于上面同一个矩阵 m，我们来创建一个新的变量 m_t 来存储 m 的转置。然后看看如果我们修改 m_t 中的值，会发生什么

In [47]:
m_t = m.T
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [48]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

实际用例


In [52]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs


array([[-0.27,  0.45,  0.64,  0.31]])

In [51]:
inputs.shape

(1, 4)

In [54]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [55]:
weights.shape

(3, 4)

所以这不可行，但是注意，如果你获取 weights 矩阵的转置，它会：

In [56]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [ ]:
如果你获取 inputs 的转置，并调换它们的顺序也可以

In [57]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

这两个答案是彼此的转置，所以你使用的乘法只取决于你想要的输出的形状。